### ISSUE TITLE
Traceback errors

### ISSUE THREAD

**Issue by TheScriptGuy** [TheScriptGuy/generate-url-requests#1]
Exception in thread Thread-75 (worker):
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/opt/venv/lib/python3.10/site-packages/urllib3/response.py", line 1076, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/response.py", line 1018, in _handle_chunk
    value = self._fp._safe_read(amt)  # type: ignore[union-attr]
  File "/usr/lib/python3.10/http/client.py", line 633, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(8192 bytes read, 2048 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/response.py", line 933, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/response.py", line 1061, in read_chunked
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/venv/lib/python3.10/site-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(8192 bytes read, 2048 more expected)', IncompleteRead(8192 bytes read, 2048 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/ConnectionManager.py", line 50, in make_request
    response = requests.get(f"{protocol}://{hostname}", timeout=5, verify=self.secure)
  File "/opt/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib/python3.10/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(8192 bytes read, 2048 more expected)', IncompleteRead(8192 bytes read, 2048 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/ThreadManager.py", line 71, in worker
    self.worker_function(item, thread_id, self.statistics_manager)
  File "/app/ConnectionManager.py", line 92, in make_request
    except requests.exceptions.ConnectTimeoutError:
AttributeError: module 'requests.exceptions' has no attribute 'ConnectTimeoutError'. Did you mean: 'ConnectTimeout'?

**Comment by TheScriptGuy** [comment]
This should be resolved now.
